import { NotificationItem } from "@/app/components/styles/client_styles/notifications/types";

export const notificationsMockData: NotificationItem[] = [
  {
    id: "n1",
    type: "contract",
    title: "Sarah Chen accepted your offer",
    meta: "Mobile App Design Project — Contract #C-2847 is now active",
    timeAgo: "31m ago",
    isUnread: true,
    actionLabel: "Contract Room",
    tags: [],
  },
  {
    id: "n2",
    type: "application",
    title: "New application from Alex Rivera",
    meta: "Full-Stack Developer Position",
    timeAgo: "1h ago",
    isUnread: true,
    actionLabel: "View Application",
    tags: ["5 years exp", "React + Node.js"],
  },
  {
    id: "n3",
    type: "payment",
    title: "Payment received",
    meta: "You received $2,500 from TechCorp Solutions",
    timeAgo: "2h ago",
    isUnread: true,
    actionLabel: "View Earnings",
    amountTag: "$2,500",
  },
  {
    id: "n4",
    type: "review",
    title: "Maya Thompson left you a 5-star review",
    meta: `"Excellent work on the e-commerce redesign. Highly recommended!"`,
    timeAgo: "3h ago",
    isUnread: false,
    actionLabel: "View Reviews",
  },
  {
    id: "n5",
    type: "milestone",
    title: "Milestone submitted for review",
    meta: "Dashboard Design Phase — Sarah Chen submitted deliverables",
    timeAgo: "4h ago",
    isUnread: false,
    actionLabel: "Review Milestone",
    tags: ["Milestone 2/3"],
  },
  {
    id: "n6",
    type: "invite",
    title: "John Davis invited you to a workspace",
    meta: `"Design Team" workspace — 4 active projects`,
    timeAgo: "6h ago",
    isUnread: false,
    actionLabel: "View Invite",
  },
  {
    id: "n7",
    type: "message",
    title: "New message from Emma Wilson",
    meta: "Can we schedule a call to discuss the project timeline?",
    timeAgo: "8h ago",
    isUnread: false,
    actionLabel: "Reply",
  },
  {
    id: "n8",
    type: "offer",
    title: "New offer from Startup Labs",
    meta: "Landing Page Development",
    timeAgo: "12h ago",
    isUnread: false,
    actionLabel: "Review & Accept",
    tags: ["Fixed $1,800", "2 weeks"],
  },
  {
    id: "n9",
    type: "proposal",
    title: "3 new proposals",
    meta: `Your job "UI/UX Designer for SaaS Platform" received 3 applications`,
    timeAgo: "16h ago",
    isUnread: false,
    actionLabel: "Review Proposals",
  },
  {
    id: "n10",
    type: "payment",
    title: "Milestone funded",
    meta: "TechCorp funded Milestone 2 ($3,000) — Frontend Development",
    timeAgo: "20h ago",
    isUnread: false,
    actionLabel: "View Project",
    amountTag: "$3,000",
  },
  {
    id: "n11",
    type: "project",
    title: "Project milestone completed",
    meta: "E-commerce Redesign — Phase 1: Design Mockups marked complete",
    timeAgo: "1d ago",
    isUnread: false,
    actionLabel: "View Project",
  },
  {
    id: "n12",
    type: "application",
    title: "New application from Lisa Park",
    meta: "Content Writer Position",
    timeAgo: "1d ago",
    isUnread: false,
    actionLabel: "View Application",
    tags: ["8 years exp", "SEO + Marketing"],
  },
];
