import { NotificationItem } from "@/app/components/styles/client_styles/notifications/types";

export const sellerNotificationsMockData: NotificationItem[] = [
  {
    id: "s1",
    type: "offer",
    title: "New sale! Premium Dashboard UI Kit",
    meta: "Sarah Chen purchased your product with Commercial License",
    timeAgo: "17m ago",
    isUnread: true,
    actionLabel: "View Order",
    amountTag: "$129.00",
    tags: ["Commercial"],
  },
  {
    id: "s2",
    type: "message",
    title: "New message from Marcus Johnson",
    meta: `Question about SaaS Template — "Does this include source files?"`,
    timeAgo: "47m ago",
    isUnread: true,
    actionLabel: "Reply",
    avatarSrc: "/images/marcus.png", // 
    avatarAlt: "Marcus Johnson",
  },
  {
    id: "s3",
    type: "payment",
    title: "Payout processed",
    meta: "Your earnings of $2,847.50 have been sent to your account",
    timeAgo: "2h ago",
    isUnread: true,
    actionLabel: "View Earnings",
    amountTag: "$2,847.50",
  },
  {
    id: "s4",
    type: "review",
    title: "Emma Rodriguez left a 5-star review",
    meta: `"Incredible quality! The components saved me weeks of work. Highly recommended!"`,
    timeAgo: "3h ago",
    isUnread: false,
    actionLabel: "View Review",
    avatarSrc: "/images/emma.png", // ✅ paste later
    avatarAlt: "Emma Rodriguez",
  },
  {
    id: "s5",
    type: "offer",
    title: "Mobile App Wireframe Kit sold",
    meta: "David Park purchased with Extended License — Order #ORD-2024-5678",
    timeAgo: "4h ago",
    isUnread: false,
    actionLabel: "View Order",
    amountTag: "$249.00",
    tags: ["Extended"],
  },
  {
    id: "s6",
    type: "project",
    title: "Product approved!",
    meta: "E-commerce Template Pro has been approved and is now live",
    timeAgo: "6h ago",
    isUnread: false,
    actionLabel: "View Product",
  },
  {
    id: "s7",
    type: "message",
    title: "Support request from buyer",
    meta: "Alex Kim needs help with customization on Dashboard Kit",
    timeAgo: "8h ago",
    isUnread: false,
    actionLabel: "Respond",
  },
  {
    id: "s8",
    type: "offer",
    title: "New sale! Landing Page Template",
    meta: "Jennifer Lee purchased with Personal License",
    timeAgo: "12h ago",
    isUnread: false,
    actionLabel: "View Order",
    amountTag: "$49.00",
    tags: ["Personal"],
  },
  {
    id: "s9",
    type: "payment",
    title: "Monthly payout scheduled",
    meta: "Your next payout of $4,285.00 will be processed on Dec 15",
    timeAgo: "16h ago",
    isUnread: false,
    actionLabel: "View Details",
    amountTag: "$4,285.00",
  },
  {
    id: "s10",
    type: "project",
    title: "License verification complete",
    meta: "Commercial license verified for Premium Dashboard UI Kit",
    timeAgo: "20h ago",
    isUnread: false,
    actionLabel: "View Product",
  },
  {
    id: "s11",
    type: "review",
    title: "New review on SaaS Template",
    meta: "Michael Brown rated your product 4 stars with feedback",
    timeAgo: "1d ago",
    isUnread: false,
    actionLabel: "View Review",
  },
  {
    id: "s12",
    type: "message",
    title: "Pre-sale question",
    meta: `Taylor Wilson: "Can I use this for multiple client projects?"`,
    timeAgo: "1d ago",
    isUnread: false,
    actionLabel: "Answer",
  },
];
